import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/16x16.png" sizes="16x16" type="image/png" />
        <link rel="icon" href="/32x32.png" sizes="32x32" type="image/png" />
        <link
          rel="apple-touch-icon"
          href="/180x180.png"
          sizes="180x180"
          type="image/png"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-sidebar`}
      >
        <Providers>
          <NuqsAdapter>{children}</NuqsAdapter>
        </Providers>
      </body>
      {process.env.NEXT_PUBLIC_ANALYTICS_GA && (
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_ANALYTICS_GA} />
      )}
    </html>
  );
}
